index.html
=> main tag change

general-navbar-style.css
height changed & Privacy-p./Legal-n. hover-Effect update
=> navbar height

index.html
Path changed in <script src="../scripts/script.js"></script>
=> index.html Path change

assets/img/Vector 5.svg, edit_contact-script.js, edit_contact-style.css, edit_contact.html
=> Edit contact

html/privacy_policy.html, styles/privacy_policy.css
generated Privacy Policy implemented as own site.
=> Privacy policy html

html/legal_notice.html, styles/legal_notice.css
=> legal_notice

html/board.html
General-navbar.html zu board.html hinzugefügt.
=> added general-navbar to board-view

html/general-navbar.html
Added </body> tag because it was missing
=> General-navbar </body> added

html/add_task.html, styles/add-task-style.css
General-Navbar added to Add Task
=> General-Navbar added to Add Task

styles/add-task-style.css, styles/assets.css
=> Close-Button hover

styles/general-navbar-style.css
Navbar-Hover-Effect für Summary-menu-buttons und Privacy Police/Legal Notice
=> general-navbar hover-effect

html/add_task.html, html/board.html, scripts/add_task-script.js, scripts/templates/addTaskOverlayTemplate.js
eventListener and FORM_ELEMENT problem solved
=> eventListener & FORM_ELEMENT problem solved

html/summary.html
General-Navbar added to Summary
=> General-navbar added to Summary

html/contacts.html
Path general-navbarscript.js added to contacts.html
=> Path "general-navbarscript.js" added to "contacts.html"

html/contacts.html
Pfad hinzugefügt von editContactOverlayTemplate.js und editContactOverlayContacts.js
=> Path added - editContactOverlay

html/contacts.html, scripts/contacts.js
Im contacts.js eine init() angelegt und eine fetch Funktion für die Kontakte.
=> implemeted init function for auto fetch onload

scripts/editContactOverlayContacts.js, scripts/templates/editContactOverlayTemplate.js
Edit-Contact-Overlay-Contacts 
Ich habe das von add-task Overlay übernommen und abgeändert
=> Edit-Contact-Overlay-Contacts

html/summary.html
- added paths to summary  (general-navbar)
- bug fixing
=> Bug fixing - Summary.html

styles/general-navbar-style.css
- General-Navbar Button :active hover deactivated 
- Cursor: default
=> General-Nav. Button active hover deactivated - Cursor: default

html/help.html, styles/help.css
Der Button ist nun korrekt positioniert und sticky
=> implemented sticky button

html/contacts.html, html/edit_contact.html, scripts/editContactOverlayContacts.js, scripts/templates/editContactOverlayTemplate.js, scripts/templates/renderContactsTemplate.js, styles/edit_contact-style.css
Jetzt funktioniert bei der Seite ContactsDetailView der Edit-Button.
=> Contacts - EditContactOverlay

html/add_task.html, scripts/add_task-script.js, styles/add-task-style.css
=> Validation-Add Task

html/add_contact.html, html/add_task.html, html/board.html, html/contacts.html, html/edit_contact.html, html/sign_up.html, index.html, scripts/board.js, scripts/contacts.js, scripts/db.js
Im Skript db.js ist nun vorerst die BASE_URL zentral enthalten.
In den HTMLS wurde das Skript verlinkt.
=> centralized-db-script

styles/general-navbar-style.css, styles/legal_notice.css
Ich hab den hover Effekt angepasst - statt scale wird bold verwendet.
=> changed hover-effekt for summary-btn

scripts/contacts.js, scripts/renderContacts.js, scripts/templates/renderContactsTemplate.js
Ich habe hier versucht, renderContacts.js und renderContactsTemplate.js aufeinander abzustimmen, damit man die Daten aus der Datenbank abrufen kann ohne "mock contacts".
=> Fetch contacts & render contacts

index.html, styles/log_in.css, styles/logo-animation.css
Ich habe einen neuen Branch erstellt - weiß nicht, ob das der ideale Weg war. Die Animation funktioniert nun.
=> implemented logo-animation

scripts/contacts.js, scripts/renderContacts.js
Fehlermeldung ist gelöst und die Kontakte werden wieder angezeigt.
=> error message and missing contacts

html/privacy_policy.html, styles/privacy_policy.css
- Pfad angepasst für Favicon
- max-width content auf 1016px gesetzt
- padding-left auf 328px gesetzt
=> Path added / max-width content / padding-left

html/board.html, scripts/board.js, scripts/templates/emptyBoardContainerTemplate.js, styles/board.css
Funktion hinzugefügt: createUserFeedbackForEmptyBoardContainers() 
Ist eine Spalte am Board leer wird nun ein User Feedback eingefügt.
=> implemented createUserFeedbackForEmptyBoardContainers()

index.html
logo animaton and styling of index.html fixed
=> Bug fix index.html: design login after merge

html/general-navbar.html, index.html, scripts/general-navbarscript.js
Der User / Gast kann sich im Dropdown-Menü ausloggen.
=> Log-out user & guest

html/summary.html
Jeder Link der Summary-page führt zum Board.
=> Each summary link linked to board

html/summary.html, scripts/contacts.js, scripts/summaryscript.js
summaryGreetingUser() 
Abhängig von der Tageszeit wird eine Begrüßungsnachricht (z.B. "Good morning, [Benutzername]") angezeigt.
getLoggedInUser():
Um den aktuell eingeloggten User zu finden.
Funktion wurde bearbeitet und läuft jetzt. Der Gast wird immer noch begrüßt, da wir uns ja nicht einig waren, ob wir das entfernen oder nicht :-D
=> summaryGreetingUser & getLoggedInUser

index.html, scripts/script.js, scripts/signUp.js, scripts/templates/failedLoginTemplate.js, styles/log_in.css
- Form validation für Login 
- Login logic (benedikt@gmail.com, 1234)
- User Feedback failed Login
Ich hab ein wenig gegoogelt und mich mal dafür entschieden den angemeldeten Benutzer im session storage zu speichern. Sobald der Browser geschlossen wird, werden diese Daten gelöscht.
Die Userdaten in einer Variablen zu speichern würde sehr viel mehr Aufwand bedeuten, da der Inhalt der Variablen beim Wechseln der Seite oder beim neu Laden verloren geht.
Wir können gerne abstimmen, welche Daten genau in den session storage kommen.
Beim Logout wäre dann wichtig, diese Daten zu löschen.
=> Log in logic

scripts/contacts.js
- Kontakte werden vor dem Rendern sortiert
=> sort contacts before rendering

html/summary.html, index.html, scripts/guestLogin.js, scripts/script.js, scripts/signUp.js, scripts/summaryscript.js, scripts/templates/failedLoginTemplate.js, styles/log_in.css
Begrüßung angepasst für den Gast
=> Edited greeting - Guest

scripts/renderContacts.js
Die doppelte renderContactDetail() entfernt
=> delete one renderContactDetail

scripts/renderContacts.js, styles/render_contacts.css
der erste Kontakt wird nun beim Aufrufen der Detail View von rechts eingeschoben. 
Weitere ToDOs:
1. Schließen der Detail View
2. Aufrufen eines anderen Kontakts Detail View
=> Feature contacts animate contact detail view

html/add_task.html, html/board.html, html/contacts.html, html/summary.html, scripts/general-navbarscript.js, scripts/userCredentials.js, styles/general-navbar-style.css
der eingeloggte User wird abgefragt: 
erst session storage und falls der leer ist dann der LocalStorage.
Falls beide leer sind ist als default ein G hinterlegt.
und die Initialen werden in der Navbar als UserButton gerendert durch die general-navbar event listener
=> Feature user show logged in user initials

html/add_task.html, html/board.html, html/contacts.html, html/help.html, html/privacy_policy.html, html/summary.html, scripts/general-navbarscript.js
<a href="#" onclick="logoutUser()">Log out</a> added to hmtl pages
=> <a href="#" onclick="logoutUser()">Log out</a> added to pages

html/sign_up.html, scripts/generateContactData.js, scripts/pushContactToDb.js, scripts/signUp.js
By submitting the sign up form:
1. all contacts will read out of the database
2. counter will be increased by one
3. a new contact key with the given parameters will be created, not given parameters will be set to ""
4. all contacts will be pushed to the database again, overwriting the old data (PUT)
=> Feature sign up create new contact in db

html/board.html, scripts/board.js, scripts/templates/boardCardAssignedUsersTemplate.js
Die Funktion  generateUserAvatars() wurde im board.js so angepasst, dass die Farbe und Initialen des Benutzers nun aus der Datenbank kommen.
=> User color and initals for the assigned users now come from the db

scripts/renderContacts.js
Klickt man auf einen Kontakt, wird die Detailansicht angezeigt.
Ein erneuter Klick auf denselben Kontakt schließt die Detailansicht wieder
=> Contacts - closeContactDetail

scripts/editContactOverlayContacts.js, scripts/templates/editContactOverlayTemplate.js, styles/edit_contact-style.css
Das Profilbild zeigt jetzt die Initialen des jeweiligen Kontakts.
=> Edit-Contact-Photo update

scripts/renderContacts.js, styles/render_contacts.css
1. Die Kontakte werden mit einer Transition geöffnet und geschlossen beim entsprechenden Klick auf den Kontakt aus der Liste. 
2. Das active Attribut wird in der Liste dementsprechend angezeigt und auch wieder entfernt.
3. Beim Wechseln des Kontakts wird der erste Kontakt mit einer Transition erst ausgeblendet und der neue Kontakt dann mit einer kurzen Verzögerung und einer Transition wieder eingeblendet. 
4. Beim Wechsel des Kontakts wechselt auch das active Attribut in der Kontakt Liste.
=> Feature contacts: Switch contact detail view

scripts/contacts.js
Ich habe die async function putContact(contact) komplett entfernt.
Es funktioniert alles :-D
=> function putContact deleted

html/board.html, scripts/boardCardDetails.js, scripts/templates/boardCardTemplate.js, scripts/templates/cardDetailsOverlayTemplate.js, styles/card.css
durch den Klick auf eine der Karten im Board wird das Overlay mit den Detailinformationen zu dem Task angezeigt.
_Weitere ToDos:_
=> Feature Board: open/close card detail overlay

scripts/editContactOverlayContacts.js, scripts/templates/editContactOverlayTemplate.js
- Beim Klicken auf den 'Save'-Button werden die Änderungen am Kontakt in die Datenbank übernommen und die Anzeige 
aktualisiert.
- Nach dem Speichern werden die Kontaktliste und die Kontaktdetails aktualisiert.
=> Edit-Contact_Save-Button

html/contacts.html, scripts/summaryscript.js
Bei contacts/editContactOverlay wird keine Fehlermeldung mehr angezeigt.
=> no more error messages

scripts/editContactOverlayContacts.js
So sieht es momentan in der "main" aus.
Der Anfang /** von JSDoc hat gefehlt. 
Jetzt funktioniert der Edit Button bei Contacts-Detail-View wieder.
=> Bug fixed - Edit/Contacts

html/board.html, scripts/contacts.js, scripts/handleTaskInDatabase.js
Ich habe die Datei **handleTaskInDatabase.js** erstellt und die Funktion async function updateTasksInDatabase(updatedTasks) aus contacts.js dorthin ausgelagert. 
Zusätzlich habe ich async function deleteTask(taskId) in diese Datei verschoben, um das Löschen von Tasks in der boardCardDetail-Ansicht zu verwalten.
=> handleTaskInDatabase.js

scripts/add_contact-script.js, scripts/contacts.js, styles/contacts.css
Leere Eingabefelder werden rot markiert, um auf fehlende Eingaben hinzuweisen. Sobald der Benutzer mit der Eingabe beginnt, wird die Markierung wieder entfernt und das Feld erhält seine ursprüngliche Farbe zurück
=> Bug empty inputs - Add new contact/Add Contact

html/contacts.html, scripts/addTaskAssigningUsers.js, scripts/board.js, scripts/contacts.js, scripts/db.js, scripts/editContactOverlayContacts.js, scripts/pushContactToDb.js, scripts/renderContacts.js, scripts/script.js, scripts/signUp.js, scripts/summaryscript.js
sowohl die Get contacts als auch die GET tasks Funktion in db.js ausgelagert und aufrufende Funktionen angepasst, sodass immer die ausgelagerte Funktion aufgerufen wird. 
Die aufrufenden Funktionen habe ich soweit möglich auch nochmal getestet, diese sollten alle noch funktionieren.
=> Outsourcing fetch functions collecting data

scripts/pushTaskToDb.js
Habe mal eine pushTaskToDb erstellt. 
Was meint ihr dazu?
=> pushTaskToDb.js

html/summary.html, scripts/summaryscript.js
Wenn alle Tasks auf Done sind "No upcoming Deadline":
Sobald ein Task nicht auf Done ist:
Die jeweilige Anzahl der Tasks wird dann in der entsprechenden Box angezeigt.
=> Feature Summary: displaying number of tasks and upcoming deadline

styles/card-details.css
Die Animation funktioniert.
Die Änderung erzeugt einen weicheren und gleichzeitig schnellen Animationseffekt.
=> Animation-BoardCardDetailOverlay

scripts/boardCardDragDrop.js, styles/card.css
Wenn die Karte per Drag & Drop verschoben wird, kippt diese animiert zur rechten Seite.
=> Animation Drag and Drop

.gitignore
.gitignore  für up.bat und up.sh
=> gitignore - up.bat / up.sh

html/board.html, scripts/boardCardDetailsEdit.js, scripts/templates/cardDetailsEditOverlayTemplate.js, scripts/templates/cardDetailsOverlayTemplate.js, styles/add-task-style.css, styles/edit-card.css
Bitte überprüfen!
Die Funktionen müssen auch noch an die aktuellen Subtasks Funktionen von Peter angepasst werden. 
Ebenso der Style.
=> Card detail view   edit task()

html/summary.html, index.html, scripts/signUp.js, scripts/summaryscript.js, scripts/templates/cardDetailsOverlayTemplate.js
Das öffnen von allen Seiten funktioniert nun ohne das irgendwelche Fehler getriggert werden.
Was ich nicht getestet habe, ob noch alle Funktionen funktionieren.
Getestet ist:
- öffnen von Tasks in Detailansicht
- login (user & guest)
- signUp
- addTask (über die addTask.html)
- contact Detailansicht
=> Bug fixing references missing

html/add_task.html, html/board.html, html/contacts.html, html/summary.html, index.html, scripts/authGuard.js, scripts/script.js
Bitte prüfen, ob es funktioniert.
Verbesserungsvorschläge nehme ich gerne entgegen. :-D 
Erinnerung:
Nicht angemeldete Besucher von Join werden werden bei geschützten Seiten (Summary, Add-Task, Board, Contacts etc.) auf die Login-Seite weitergeleitet
=> checkIfUserIsLoggedIn()

scripts/general-navbarscript.js
- funktion logoutUser() 
- Logs out the current user and clears all local/session data.
=> Bug fixed - clear()

scripts/addTaskSubtasks.js, scripts/boardCardDetailsEdit.js
Die Funktion initSubtasks() wurde gelöscht, da sie keine Verwendung hat.
=> deleted unused function initSubtasks()

scripts/templates/renderContactsTemplate.js, styles/render_contacts.css
ContactDetailView - Edit & Delete Button
Hover-Effekt: Text und Icon der Buttons werden beim Mouseover farblich hervorgehoben.
Die Eigenschaften der Buttons habe ich zusammengefasst.
=> ContactDetailView - Edit/Delete Button hover

html/board.html, scripts/addTaskOverlayBoard.js, scripts/pushTaskToDb.js, scripts/templates/cardDetailsEditOverlayTemplate.js, styles/edit-card.css
- In der Spalte, in der das addTaskOverlay geöffnet wird, wird der Task hinzugefügt
=> Feature create task for correct column

html/add_task.html, scripts/addTaskAssigningUsers.js
Der eingeloggte User wird als erster in der "Assigned to"-Liste angezeigt und erscheint nicht doppelt in der Liste.
=> function prioritizeLoggedInUser(contacts)

html/add_task.html, scripts/addTaskAssigningUsers.js, scripts/addTaskOverlayBoard.js, scripts/boardCardDetailsEdit.js, scripts/templates/addTaskOverlayTemplate.js, scripts/templates/cardDetailsEditOverlayTemplate.js, styles/add-task-style.css
In diesem Branch ging es darum, dass sich das Dropdown-Menü für die zugewiesenen Benutzer öffnen und schließen lässt.
Es gibt nun einen Code auf den alle drei Ansichten (add_task.html, AddTaskOverlay und EditCardOverlay) zugreifen.
=> Feature close assigned to overlay

scripts/templates/addContactOverlayTemplate.js, styles/add_contact-style.css, styles/add_contact_overlay.css
Klassen für die Buttons angepasst und vereinheitlicht
=> Bug Fix contacts.html: add contact buttons

scripts/boardCardDetailsEdit.js, scripts/script.js, styles/logo-animation.css
Fehlende Klammer bei saveEditTask() in boardCardDetailsEdit.js
Klammer zu viel bei @keyframes hideOverlaylogo-animation.css
=> bracket error

styles/sign_up.css
=> Responsive sign up.html

scripts/general-navbarscript.js, styles/general-navbar-style.css
In Figma wurde der Hover-Effekt für mobile Geräte entfernt, sodass nur der Active-Effekt beibehalten wurde. Daher habe ich auch den Hover-Effekt entfernt.
=> setActiveButtonForMobile()

scripts/boardCardDetailsEdit.js
Es war nur eine Klammer falsch gesetzt. Der Edit-View lässt sich wieder öffnen.
=> fixed editTask bug

html/summary.html, scripts/authGuard.js, scripts/board.js, scripts/boardSearch.js, scripts/general-navbarscript.js, scripts/script.js
Das Projekt wurde einmal auf den Server abgelegt und geprüft. 
https://join-429.developerakademie.net/Join/index.html
Dabei sind einige Fehlermeldungen aufgetaucht welche behoben wurden. Die aktuelle Version mit Änderungen findet ihr schon auf dem Server.
Grundsätzlich sind einige Bugs noch aufgefallen, die aber unabhängig vom Server noch bestehen. Diese wurden als Bugs in Trello aufgenommen.
=> Bug fix server problems

styles/add-task-style.css
das generelle Design von addTask angepasst und Responsive Design hinzugefügt. 
Breakpoints:
320px
769px
1025px
1201px
4K
=> Responsive add task.html

html/help.html, scripts/general-navbarscript.js, styles/edit-card.css
- Im head hinzugefügt : <script src="../scripts/userCredentials.js"></script>
- Das Help-Symbol wird ausgeblendet, wenn man sich auf der Seite befindet.
=> Bug fixed / dropdown / signal for help

styles/card-details.css
Durch Änderungen wurde unser Style bei Board-card-detail verändert.
Habe es wieder angepasst:
=> Bug-Board-Card-details.css

scripts/boardCardDetailsEdit.js
Assigned to lässt sich wieder öffnen im Edit-Overlay.
=> Assigned to - Dropdown menu

html/add_task.html, html/board.html, html/contacts.html, html/help.html, html/legal_notice.html, html/privacy_policy.html, html/sign_up.html, html/summary.html, index.html, scripts/checkLandscape.js, styles/landscape.css
board und contacts.html müssen im Nachgang einmal geprüft werden. 
Die beiden Seiten waren noch nicht für die mobile Ansicht optimiert.
=> Feature check landscape mode

styles/edit-card.css
- high: 100vh; wurde entfernt, da es nicht benötigt wird
=> delete - high: 100vh

scripts/board.js
Die Karten bleiben nach dem Neuladen an ihrem Platz und es entstehen keine Duplikate!
=> Bug fixed - Board Card

scripts/checkLandscape.js
Die Funktion des landscape-warning auf die Seiten index.html (login) und signUp.html erweitert.
Es gibt nun keine Fehlermeldungen mehr auf den Seiten und das landscape-warning wird korrekt ausgeführt. 
Überlagerte div war auf beiden Seiten schon vorhanden.
JSDoc hatte auch noch gefehlt
=> Bug Fix:  landscape warning index.html & signUp.html

styles/board.css, styles/card-details.css
Jede Card-Container-Spalte ist scrollbar, während der Body fixiert bleibt. 
Bitte testen, ob das so passt.
=> Cards scrollbar/side static

scripts/boardCardDetails.js, scripts/handleTaskInDatabase.js, scripts/templates/cardDetailsOverlayTemplate.js
deleteTask() wird jetzt wieder aufgerufen und auch die Datenbank sowie das Board aktualisiert. 
Das Schließen der CloseCardDetail Funktion habe ich um den delete Button erweitert.
=> Bug Fix:  delete task

scripts/boardCardDragDrop.js, styles/board.css, styles/card.css
Bitte mal testen.
=>
Wenn eine Karte per Drag-and-Drop gehalten wird und sich der Zeiger bzw. Finger nahe dem oberen oder unteren Rand des Bildschirms befindet, soll die Seite automatisch in die entsprechende Richtung scrollen.
Bei mir funktioniert es mal und dann wieder nicht :-/
=> Story board   mobile drag&drop

scripts/general-navbarscript.js
sowohl der User Button in der general-navbar als auch das assigend To hatten eine Funktion toggleDropdown() ..
--> die Funktion in der GeneralNavbar umbenannt, hat das Problem behoben
=> fixed toggle of assigned Users in addTask

styles/card.css
Bitte überprüfen, ob der vertikale Scrollbalken im Card-Container des Boards noch angezeigt wird.
=> Vertikaler scrollbalken-overflow-y: hidden

scripts/add_contact-script.js, scripts/contacts.js
**Der Kontakt kann erst erstellt werden, nachdem alle Eingabefelder korrekt ausgefüllt wurden.**
**Die Fehlermeldung, die nach dem Klicken des 'Delete'-Buttons auftrat, wurde behoben.**
VOR DEM LÖSCHEN:
NACH DEM LÖSCHEN:
=> Add contact  form validation

scripts/add_contact-script.js, scripts/contacts.js, scripts/editContactOverlayContacts.js
Habe den Code von Jessica leicht umgebaut, sodass ein Parameter übergeben wird. Damit kann der Code für die Form Validation für das addContact- und das editContact-Overlay verwendet werden.
=> Feedback form validation overlays addand edit contact

html/add_task.html, html/board.html, scripts/pushTaskToDb.js
Beim Erstellen einer Task wird ein UserFeedback abhängig von dem Status Code des Rest Calls für 3Sekunden angezeigt.
Nach der Zeit wird immer zur board.html weitergeleitet.
Dabei ist unabhängig ob der Task über das addTaskOverlay oder die addTask Seite ausgeführt wird.
=> Feature: add task user feedback

html/add_task.html, scripts/templates/addTaskOverlayTemplate.js, styles/add-task-style.css
Zu den beiden leeren Listen eine minimal Höhe hinzugefügt, um die Höhe vorher bereits festzulegen. 
Beim Anlegen von Subtask oder hinzufügen von Usern zum Task bleibt das Formular nun statisch.
funktioniert auch fürs responsive Design
=> Bug Fix: add task adding subtask / assigned to

html/add_task.html, html/board.html, scripts/addTaskDueDate.js, scripts/addTaskOverlayBoard.js, scripts/add_task-script.js, scripts/boardCardDetailsEdit.js, scripts/pushTaskToDb.js, scripts/templates/addTaskOverlayTemplate.js, scripts/templates/cardDetailsEditOverlayTemplate.js, styles/add-task-style.css
Den Datepicker für das due-date input Feld auf allen drei Seiten/Overlays implementiert. 
Lediglich bei dem CardEditOverlay wird setDefaultDate() nicht aufgerufen, da ja das aktuelle Datum aus der Datenbank angezeigt werden soll. 
In dem Datepicker selber lassen sich nur Tage ab dem aktuellen Tag auswählen
=> Feature: addTask datepicker input for due_date

scripts/board.js, styles/card.css
Wenn mehr als drei Benutzer für eine Aufgabe ausgewählt wurden, wird ab dem vierten Benutzer ein ‚+‘-Symbol angezeigt, das die Anzahl der zusätzlich ausgewählten Benutzer anzeigt.
=> Board card symbol

styles/add-task-style.css
Scrollbar eleminiert durch erweitertes padding auf dem main Attribut.
=> added additional style to main to hide vertical scrollbar

styles/render_contacts.css
Wie im Feedback erwähnt wurde die Schriftgröße bei den Kontakten auf 16px erhöht.
=> edited font sizes

scripts/contacts.js
Wird ein neuer Kontakt erstellt, werden nun die Details des Kontakts angezeigt, der erstellte Kontakt wird außerdem auf "active" gesetzt.
=> newly added contact details are displayed and set as active

styles/card.css
Man kann wieder die Card-container scrollen.
=> scrollbar board check

html/add_task.html, styles/add-task-style.css
Bitte Marcel teste mal, ob das so in Ordnung geht bei Add Task.
Sollte funktionieren :-)
=> Add task page main width

html/summary.html, scripts/summaryscript.js, styles/summary.css
Die mobile Ansicht wurde überarbeitet: 
Das Bild entfernt und das Layout auf reinen Text reduziert (fetter Titel und Untertitel).
=> Join-logo < 570px

scripts/summaryscript.js, styles/summary.css
JSDoc hat zu einem Fehler geführt.
Alte Code-Reste entfernt, hatten zu Fehlern in der Konsole geführt.
=> Bug-summaryscript.js

scripts/addTask.js, scripts/addTaskAssigningUsers.js, scripts/addTaskSubtasks.js, scripts/boardCardDetails.js, scripts/boardCardDetailsEdit.js, scripts/renderContacts.js
Im editView der Tasks werden alle Daten des Tasks angezeigt. Genauso lassen sich alle Daten editieren und mit einem Klick auf "OK" speichern.
Falls in einem View die Subtasks mal nicht angezeigt werden, liegt das nur am Platzmangel, also sie sind da werden aber nicht eingeblendet. Ich weiß nicht, was genau inzwischen mit Responsive weitergegangen ist, ist aber dann eher einfach zu lösen, falls das Thema noch besteht.
=> Feedback card edit view

index.html, scripts/addTaskDueDate.js, scripts/summaryscript.js
server Probleme bei Abgabe 2 gefixed
=> Bug fix server problems pt.2

html/signUp.html, scripts/signUp.js, styles/signUp.css
Die Form Felder werden nun **alle** validiert und bei nicht entsprechender Validierung mit einem roten Kasten markiert. 
Allerdings wird die Validierung erst angestoßen, wenn man zuvor einmal auf das entsprechende Input Feld geklickt hat.
=> Bug fix sign up user feedback

styles/addTask.css
Responsive des AddTask-Overlays. Es ist nun scrollbar und auch bei kleinen Bildschirmen verwendbar.
=> Bug fix responsive add task

scripts/addTaskSubtasks.js
Beim Bearbeiten der SubTasks hat sich das AddTask-Overlay geschlossen.
=> solved propagation problem

styles/generalNavbar.css, styles/summary.css
Das Dashboard ist vollständig über eine Scrollbar einsehbar.
=> Summary responsive mobile

styles/login.css
=> adjusted responsiveness to minimum 320x420px

styles/addContactOverlay.css
Add contact - responsive - max-height
=> Add contact responsive max height

html/signUp.html, scripts/signUp.js, styles/signUp.css, styles/standard.css
Ich hab das Responsive der SignUp-Page nochmal ergänzt:
Die Formvalidierung zeigt nun neu eine Meldung:
- Wenn der Name Sonderzeichen (außer -) und Zahlen enthält
- Wenn die Mail kein @ und . hat
Der SignUp Button ist nun aktiv, wenn alle Felder korrekt ausgefüllt sind, selbst wenn die Privacy Policy nicht angehakt ist.
Klickt man dann auf "Sign Up" wird der Container mit der Privacy Policy hervorgehoben.
=> Feedback sign up responsive and validation

scripts/templates/editContactOverlayTemplate.js, styles/addContactOverlay.css, styles/editContact.css, styles/renderContacts.css
Das edit responsive für die Hohe überarbeitet. 
Bis zu min-height 420px sollte alles responsive sein (zumindest für mobile)..
=> Feedback responsive edit contact

styles/editCard.css
Die Edit-Karte im Board wurde so angepasst, dass sie sich an verschiedene Bildschirmhöhen anpasst und nicht mehr abgeschnitten wird.
=> Board Edit Card max-height

styles/addTask.css
Die h1 bei AddTask.html war versetzt, da ein margin-top vorhanden war.
=> margin edited

styles/summary.css
Bei min-height von 445px kann man das dashboard scrollen.
=> responsiv card-height

styles/addContactOverlay.css
=> BugFix add contact button

styles/signUp.css
Ab einer Höhe von 650px lässt sich die LogIn Seite nun scrollen.
=> Feedback responsive sign up height

styles/addContactOverlay.css, styles/editContact.css
=> Edit contact responsive bug

styles/addContactOverlay.css
=> edit-contact close button

styles/summary.css
Bei der mobilen Ansicht gibt es keinen Scrollbalken mehr.
=> mobile scrollbar deleted
